version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: yarn install
  lint:
    steps:
      - run:
          name: Lint
          command: yarn lint
  build:
    steps:
      - run:
          name: Build packages
          command: yarn build
  test:
    steps:
      - run:
          name: Test
          command: yarn test
  save-cache:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  persist-to-workspace:
    steps:
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Move to dist folder
          command: cd ~/repo
      - run:
          name: Publish package
          command: npm publish --access public

  run-all:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - install
      - lint
      - save-cache
      - persist-to-workspace
  run-deploy:
    steps:
      - build
      - deploy

jobs:
  v12:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - run-all
      - run-deploy
workflows:
  node:
    jobs:
      - v12
