version: 2.1

commands:
  install:
    steps:
      - run:
          name: Install dependencies
          command: yarn install
  lint:
    steps:
      - run:
          name: Lint
          command: yarn lint
  build:
    steps:
      - run:
          name: Build packages
          command: yarn build
  test:
    steps:
      - run:
          name: Test
          command: yarn test
  save-cache:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  run-all:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - lint
      - size
      - install
      - save-cache

jobs:
  v12:
    docker:
      - image: node:12.9.1-browsers
    steps:
      - run-all
workflows:
  node:
    jobs:
      - v12
